server:
  port: 1111



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
